In [1]:
import pandas as pd
msg = pd.read_csv('dataset.csv',names=['message','label'])
msg

                                  message  label
0                                 message  label
1                    I love this sandwich      1
2                This is an amazing place      1
3      I feel very good about these beers      1
4                    This is my best work      1
5                    What an awesome view      1
6           I do not like this restaurant      0
7                I am tired of this stuff      0
8                  I can't deal with this      0
9                    He is my sworn enemy      0
10                    My boss is horrible      0
11               This is an awesome place      1
12  I do not like the taste of this juice      0
13                        I love to dance      1
14      I am sick and tired of this place      0
15                   What a great holiday      1
16         That is a bad locality to stay      0
17         We will have good fun tomorrow      1
18       I went to my enemy's house today      0

In [2]:
X = msg.message
y = msg.label
X

0                                   message
1                      I love this sandwich
2                  This is an amazing place
3        I feel very good about these beers
4                      This is my best work
5                      What an awesome view
6             I do not like this restaurant
7                  I am tired of this stuff
8                    I can't deal with this
9                      He is my sworn enemy
10                      My boss is horrible
11                 This is an awesome place
12    I do not like the taste of this juice
13                          I love to dance
14        I am sick and tired of this place
15                     What a great holiday
16           That is a bad locality to stay
17           We will have good fun tomorrow
18         I went to my enemy's house today
Name: message, dtype: object

In [3]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size=0.20,random_state=0)
xtrain

14        I am sick and tired of this place
16           That is a bad locality to stay
6             I do not like this restaurant
4                      This is my best work
2                  This is an amazing place
5                      What an awesome view
13                          I love to dance
9                      He is my sworn enemy
7                  I am tired of this stuff
17           We will have good fun tomorrow
11                 This is an awesome place
3        I feel very good about these beers
0                                   message
15                     What a great holiday
12    I do not like the taste of this juice
Name: message, dtype: object

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
xtrain_dtm = count_vect.fit_transform(xtrain)
xtest_dtm = count_vect.transform(xtest)

In [5]:
df = pd.DataFrame(
    xtrain_dtm.toarray(),  # This is your data matrix
    columns=count_vect.get_feature_names_out()  # Use feature names as columns, not as index
)
df

,about,am,amazing,an,and,awesome,bad,beers,best,dance,...,this,tired,to,tomorrow,very,view,we,what,will,work
0,0,1,0,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,1
4,0,0,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
5,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
6,0,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,1,0
10,0,0,0,1,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
14,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [6]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(xtrain_dtm,ytrain)
predicted = clf.predict(xtest_dtm)

In [7]:
from sklearn import metrics
print("Accuracy = ",metrics.accuracy_score(ytest,predicted))

Accuracy =  0.5

In [8]:
print('\n Confusion matrix')
print(metrics.confusion_matrix(ytest,predicted))

 Confusion matrix
[[1 2]
 [0 1]]

In [9]:
CR = metrics.classification_report(ytest,predicted)
print('Classification_report', CR)

Classification_report               precision    recall  f1-score   support

           0       1.00      0.33      0.50         3
           1       0.33      1.00      0.50         1

    accuracy                           0.50         4
   macro avg       0.67      0.67      0.50         4
weighted avg       0.83      0.50      0.50         4